// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbGDu2kCPJhTerbeHU6Y1dhHRN-gv9HYU',
    appId: '1:367237549410:web:ef35f56a4c3936e20e703b',
    messagingSenderId: '367237549410',
    projectId: 'divinity-f76d8',
    authDomain: 'divinity-f76d8.firebaseapp.com',
    storageBucket: 'divinity-f76d8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaUxGVn0G6-ITg3x5zjDltIqcQsOL7-y4',
    appId: '1:367237549410:android:584733084c619a3b0e703b',
    messagingSenderId: '367237549410',
    projectId: 'divinity-f76d8',
    storageBucket: 'divinity-f76d8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnhC8Q9saXW68LGKZTqtW9qMoTBIxFVj0',
    appId: '1:367237549410:ios:3cda7ef3489aec420e703b',
    messagingSenderId: '367237549410',
    projectId: 'divinity-f76d8',
    storageBucket: 'divinity-f76d8.appspot.com',
    iosBundleId: 'com.example.divinity',
  );
}
